apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: azure-arc-minio
  namespace: arc-k8s-minio
spec:
  releaseName: arc-k8s-minio
  chart:
    git: https://github.com/minio/operator
    ref: master
    path: helm/operator
  values:
    rootUser: "rootuser"
    rootPassword: "rootpass123"
    replicas: 3
    persistence:
      storageClass: "ase-node-local"
      size: 2Gi
